//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPMS.DAL.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPMSEntities : DbContext
    {
        public PPMSEntities()
            : base("name=PPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GovernmentHolidayTable> GovernmentHolidayTables { get; set; }
        public virtual DbSet<Pro_CapacityPlanning> Pro_CapacityPlanning { get; set; }
        public virtual DbSet<Pro_Category> Pro_Category { get; set; }
        public virtual DbSet<Pro_DailyPlan> Pro_DailyPlan { get; set; }
        public virtual DbSet<Pro_HandsetAssemblyAndPacking> Pro_HandsetAssemblyAndPacking { get; set; }
        public virtual DbSet<Pro_HandsetBattery> Pro_HandsetBattery { get; set; }
        public virtual DbSet<Pro_HandsetHousing> Pro_HandsetHousing { get; set; }
        public virtual DbSet<Pro_HandsetSmt> Pro_HandsetSmt { get; set; }
        public virtual DbSet<Pro_Line> Pro_Line { get; set; }
        public virtual DbSet<Pro_MaterialRules> Pro_MaterialRules { get; set; }
        public virtual DbSet<Pro_PlanTable> Pro_PlanTable { get; set; }
        public virtual DbSet<Pro_Product> Pro_Product { get; set; }
        public virtual DbSet<Pro_Shift> Pro_Shift { get; set; }
        public virtual DbSet<Pro_Team> Pro_Team { get; set; }
        public virtual DbSet<Pro_Type> Pro_Type { get; set; }
        public virtual DbSet<ProjectCategorization> ProjectCategorizations { get; set; }
    }
}
