//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPMS.DAL.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CellPhoneProjectEntities : DbContext
    {
        public CellPhoneProjectEntities()
            : base("name=CellPhoneProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CmnRole> CmnRoles { get; set; }
        public virtual DbSet<CmnUserRole> CmnUserRoles { get; set; }
        public virtual DbSet<CmnUser> CmnUsers { get; set; }
        public virtual DbSet<ProjectMaster> ProjectMasters { get; set; }
        public virtual DbSet<ProjectOrderQuantityDetail> ProjectOrderQuantityDetails { get; set; }
        public virtual DbSet<ProjectOrderShipment> ProjectOrderShipments { get; set; }
        public virtual DbSet<ProjectPurchaseOrderForm> ProjectPurchaseOrderForms { get; set; }
        public virtual DbSet<ProPlanTable> ProPlanTables { get; set; }
        public virtual DbSet<ProjectCategorization> ProjectCategorizations { get; set; }
    }
}
